stages:
  - build
  - package
  - deploy

  maven-build:
  image: maven:3-jdk-21
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar

  maven-test-jdk-7:
  image: maven:3-jdk-21
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar
